=== davidagtz/Charcoal-Calculator/src/renderer/themes/themes.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "title": "Charcoal Theme",
    "description": "Provides a color scheme for Charcoal",
    "properties": {
        "Graph": {
            "type": "object",
            "properties": {
                "background": {
                    "type": "string"
                },
                "axis": {
                    "type": "string"
                },
                "font": {
                    "type": "string"
                },
                "equationColors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "uniqueItems": true,
                    "minItems": 1
                }
            },
            "required": ["background", "axis", "font", "equationColors"]
        },
        "Calculator": {
            "type": "object",
            "properties": {
                "input": {
                    "type": "object",
                    "properties": {
                        "font": {
                            "type": "string",
                            "description": "Sets the font for the entire application"
                        },
                        "answerFont": {
                            "type": "string"
                        },
                        "answerBackground": {
                            "type": "string"
                        },
                        "background": {
                            "type": "string",
                            "description": "Sets the main background of the entire application"
                        }
                    },
                    "required": ["font", "answerFont", "answerBackground", "background"]
                },
                "background": {
                    "type": "string"
                },
                "font": {
                    "type": "string"
                }
            },
            "required": ["input", "background", "buttons"]
        },
        "TitleBar": {
            "type": "object",
            "properties": {
                "font": {
                    "type": "string"
                },
                "background": {
                    "type": "string"
                },
                "buttons": {
                    "type": "object",
                    "properties": {
                        "submenuhover": {
                            "type": "string"
                        }
                    },
                    "required": ["submenuhover"]
                }
            },
            "required": ["font", "background", "buttons"]
        },
        "defaultButtons": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "string"
                },
                "hover": {
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "font": {
                    "type": "string"
                }
            },
            "required": ["active", "hover", "color", "font"]
        }
    },
    "required": ["Graph", "Calculator", "TitleBar", "defaultButtons"]
}

=== davidagtz/Charcoal-Calculator/src/renderer/styles/themes/Smoke.json
{
    "Graph": {
        "background": "#FFF",
        "axis": "#333",
        "font": "#000",
        "equationColors": ["#ff8000", "#00f", "#0f0"]
    },
    "Calculator": {
        "input": {
            "font": "#000",
            "answerFont": "#FFF",
            "answerBackground": "#FFFFF",
            "background": "#FFF"
        },
        "background": "#f0f0f0",
        "font": "#333",
        "buttons": {
            "active": "#999",
            "hover": "#888"
        }
    },
    "TitleBar": {
        "font": "#FFF",
        "background": "#777",
        "buttons": {
            "submenuhover": "#444"
        }
    },
    "defaultButtons": {
        "active": "#333",
        "hover": "#555",
        "color": "#777",
        "font": "#FFF"
    }
}

=== davidagtz/Charcoal-Calculator/src/renderer/themes/Charcoal.json
{
    "Graph": {
        "background": "#000",
        "axis": "#FD971F",
        "font": "#FFF",
        "equationColors": ["#02a2ff", "#ff0252", "#52ff02"]
    },
    "Calculator": {
        "input": {
            "font": "#000",
            "answerFont": "#FFF",
            "answerBackground": "#686868",
            "background": "#FFF"
        },
        "background": "#3F3F3F",
        "font": "#FFF",
        "buttons": {
            "active": "#994d00",
            "hover": "#cc6600"
        }
    },
    "TitleBar": {
        "font": "#FFF",
        "background": "#111",
        "buttons": {
            "submenuhover": "#232323"
        }
    },
    "defaultButtons": {
        "hover": "#2b2b2b",
        "active": "#191919",
        "font": "#FFF",
        "color": "#222222"
    }
}
